trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@2
  inputs:
    versionSpec: '16.x'
    addToPath: true

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm test
  displayName: 'Run tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-results.xml'
    testRunTitle: 'Unit Tests'
    mergeTestResults: true
    failTaskOnFailedTests: true
